name: JobTrack CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Compile Python files
        run: |
          python -m py_compile app/__init__.py
          python -m py_compile app/routes.py
          python -m py_compile app/models.py
          python -m py_compile run.py

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t jobtrack:gunicorn .

      - name: Tag Docker image
        run: |
          docker tag jobtrack:gunicorn \
            100247989016.dkr.ecr.ap-south-1.amazonaws.com/jobtrack:gunicorn

      - name: Push Docker image to ECR
        run: |
          docker push \
            100247989016.dkr.ecr.ap-south-1.amazonaws.com/jobtrack:gunicorn

      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster jobtrack-cluster \
            --service jobtrack-service \
            --force-new-deployment

      - name: Wait for ECS deployment
        run: |
          aws ecs wait services-stable \
            --cluster jobtrack-cluster \
            --services jobtrack-service
